### ISSUE TITLE
Publishing on the Terraform registry

### ISSUE THREAD

**Issue by moritzheiber** [drewsonne/terraform-provider-gocd#48]
Since Terraform 0.10.6 there are other ways of [publishing third party providers without having to be included in the official Hashicorp provider organization](https://www.terraform.io/docs/registry/modules/publish.html). I think it would be really convenient for this provider to be published over there.

**Comment by moritzheiber** [comment]
I misunderstood the meaning behind the intent of the registry. It's only for modules, not providers. My bad.

**Comment by MPV** [comment]
Would you be open to reconsidering this?

Terraform is adding support for Providers in their registry: 
https://www.hashicorp.com/blog/announcing-providers-in-the-new-terraform-registry/
